# Generated by Django 5.2.8 on 2025-12-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit"), ("bonus", "Bonus")],
                max_length=10,
            ),
        ),
    ]
