# Generated by Django 5.2.8 on 2025-12-01 12:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
