# Generated by Django 5.2.8 on 2025-12-02 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0003_transaction_transaction_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
