# Generated by Django 5.2.8 on 2025-12-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0004_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("bonus", "Bonus"),
                    ("fee", "Fee"),
                ],
                max_length=10,
            ),
        ),
    ]
