# Generated by Django 5.2.8 on 2025-12-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0005_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
