# Generated by Django 5.2.8 on 2025-12-02 08:23
from decimal import Decimal

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_system_account(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    User = apps.get_model("account", "User")
    BankAccount = apps.get_model("account", "BankAccount")

    system_user = User.objects.create(
        email="system@simplebank.internal",
        password="!",
        is_active=False,
        is_staff=False,
    )

    BankAccount.objects.create(
        user=system_user, account_number="0000000000", balance=Decimal("0.00")
    )


def reverse_system_account(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    User = apps.get_model("account", "User")
    try:
        system_user = User.objects.get(email="system@simplebank.internal")
        system_user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RunPython(create_system_account, reverse_system_account),
    ]
